### ISSUE TITLE
some error when use app_container function

### ISSUE THREAD

**Issue by korterling** [RinteRface/shinyMobile#244]
I wanted to use an iframe in shinyMobile ，like this:

tags$iframe(src = "https://www.abc.com", style = "width:50%;height:600px;"),

but it is not adapted  to  shinyMobile, looks ugly.

I found an function app_container , but I found an error when use app_container :

Error in app_container(url = "https://www.abc.com") : 
  could not find function "app_container"

**Comment by DivadNojnarg** [comment]
Hi,

`app_container` is an internal (non exported) function and is not designed for this. It is actually used by `preview_mobile` which allows to display a shinyMobile app within a nice iframe container, but definitely not for using inside a shinyMobile app.
I also would not recommend to use iframes since mobile screens are too tight to get the content correctly displayed.  
In your case, if you put `width: 100%` this should improve the display.
