### ISSUE TITLE
DatePicker initial open

### ISSUE THREAD

**Issue by Seyphaton** [RinteRface/shinyMobile#53]
Hi,

the Datepicker opens during initialization.
I guess this is on purpose:
I already saw that this is triggered in the datePickerInputBinding.js:

```
        // need to trigger a click
        // close the picker to initiate it properly but need Timeout
        // otherwise the date picker cannot open anymore
        init: function(datePicker) {
          datePicker.open();
          // minimum timeout value: 4 ms (HTML5 spec)
          setTimeout(function() {datePicker.close();}, 4);
        }
```

Is there any way to make this popover invisible?
Thanks in advance.

Best regards
Seyphaton

**Comment by Seyphaton** [comment]
I am currently using this workaround:
![image](https://user-images.githubusercontent.com/23493879/72542535-9b443b00-3884-11ea-9c75-031cc47381e9.png)

**Comment by DivadNojnarg** [comment]
Thanks for the report. Indeed this would do the job:

```javascript
if (typeof value === "undefined") {
      return JSON.parse($(el).attr("placeholder"));
}
```

I also added the JSON.parse since only returning the placeholder attr does not display well. 
Actually, in other input bindings, we only have to call the get input method, as folllows:
```javascript
var d = app.calendar.get($(el));
return d.value;
```
It does not work for pickers (including the datePicker) and I cannot figure out why.

**Comment by Seyphaton** [comment]
Great, thanks for the fast response.
I tried several ways to get the value, but they all failed aswell - no idea how to fix it properly.
